Small improvements in Cache search
spotlightify/spotlightify pull request #62
Opened 2020-09-22 16:51 UTC by Marianito412

I feel like this improved the search, I got a bunch of songs that wouldn't perviously show up to show up. Try and test it with song names that include symbols.
Tested with:
**Knockin' On heaven's door
Don't look back in anger
¡Viva la Gloria!**

2020-09-29 22:40 UTC, MarkMcMoran commented
I'm currently reviewing this PR. I will test it on my machine and return with my findings.

2020-09-29 23:07 UTC, MarkMcMoran requested changes

2020-09-29 23:07 UTC, MarkMcMoran commented on spotlight/commands/play.py
> +        def by_name(x):
Can you please rename this function? I can see that it is looking for special characters, if it is referenced elsewhere it will be make sense.

2020-09-29 23:07 UTC, MarkMcMoran commented on spotlight/commands/play.py
>          L = list(cache[f'{self._type if self._type != "queue" else "song"}s'].items())
Can you use a different variable name for this please? It's very vague.

2020-09-29 23:07 UTC, MarkMcMoran commented on spotlight/commands/play.py
>              removables = ["@", "'", '"', "¡", "!", "#", "$", "%", ".", ","]
Can you remove this, it's duplication of by_name func.

2020-09-30 11:28 UTC, MarkMcMoran commented
This works fine, but please consider the changes outlined :)

2020-10-03 02:17 UTC, Marianito412 commented
Sorry for the late response, I've tried implementing all the outlined changes.

2020-10-07 22:46 UTC, MarkMcMoran commented
Great work @Marianito412, just reviewed and validation that the implemented changes are functional. @petergmurphy  I am happy enough to approve this PR.

2020-10-08 00:18 UTC, petergmurphy commented
@Marianito412 Thank you for your contribution to the project. @MarkMcMoran Thank you for the review.

2020-10-08 00:18 UTC, merged